# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tbmatch/crash.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from tbrpc import tbrpc_pb2 as tbrpc_dot_tbrpc__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='tbmatch/crash.proto',
  package='tbmatch',
  syntax='proto2',
  serialized_pb=_b('\n\x13tbmatch/crash.proto\x12\x07tbmatch\x1a\x11tbrpc/tbrpc.proto\"a\n\x12\x43rashReportRequest\x12\x10\n\x08\x61pp_name\x18\x01 \x01(\t\x12\x15\n\rbuild_version\x18\x02 \x01(\t\x12\x12\n\nmachine_id\x18\x03 \x01(\t\x12\x0e\n\x06\x62undle\x18\x04 \x01(\x0c\x32T\n\x12\x43rashReportService\x12>\n\x0b\x43rashReport\x12\x1b.tbmatch.CrashReportRequest\x1a\x0c.tbrpc.Empty\"\x04\xc8\xf3\x18\x00')
  ,
  dependencies=[tbrpc_dot_tbrpc__pb2.DESCRIPTOR,])




_CRASHREPORTREQUEST = _descriptor.Descriptor(
  name='CrashReportRequest',
  full_name='tbmatch.CrashReportRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='app_name', full_name='tbmatch.CrashReportRequest.app_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='build_version', full_name='tbmatch.CrashReportRequest.build_version', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='machine_id', full_name='tbmatch.CrashReportRequest.machine_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bundle', full_name='tbmatch.CrashReportRequest.bundle', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=148,
)

DESCRIPTOR.message_types_by_name['CrashReportRequest'] = _CRASHREPORTREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CrashReportRequest = _reflection.GeneratedProtocolMessageType('CrashReportRequest', (_message.Message,), dict(
  DESCRIPTOR = _CRASHREPORTREQUEST,
  __module__ = 'tbmatch.crash_pb2'
  # @@protoc_insertion_point(class_scope:tbmatch.CrashReportRequest)
  ))
_sym_db.RegisterMessage(CrashReportRequest)



_CRASHREPORTSERVICE = _descriptor.ServiceDescriptor(
  name='CrashReportService',
  full_name='tbmatch.CrashReportService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=150,
  serialized_end=234,
  methods=[
  _descriptor.MethodDescriptor(
    name='CrashReport',
    full_name='tbmatch.CrashReportService.CrashReport',
    index=0,
    containing_service=None,
    input_type=_CRASHREPORTREQUEST,
    output_type=tbrpc_dot_tbrpc__pb2._EMPTY,
    options=_descriptor._ParseOptions(descriptor_pb2.MethodOptions(), _b('\310\363\030\000')),
  ),
])
_sym_db.RegisterServiceDescriptor(_CRASHREPORTSERVICE)

DESCRIPTOR.services_by_name['CrashReportService'] = _CRASHREPORTSERVICE

# @@protoc_insertion_point(module_scope)
