# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tbmatch/session.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from tbrpc import tbrpc_pb2 as tbrpc_dot_tbrpc__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='tbmatch/session.proto',
  package='tbmatch',
  syntax='proto2',
  serialized_pb=_b('\n\x15tbmatch/session.proto\x12\x07tbmatch\x1a\x11tbrpc/tbrpc.proto\"f\n\x0cLoginRequest\x12\r\n\x05login\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\x15\n\rbuild_version\x18\x05 \x01(\t\x12\x1e\n\x16__deprecated_remote_ip\x18\n \x01(\t\"L\n\x1aGetGameSessionTicketResult\x12\x1f\n\x04game\x18\x01 \x01(\x0e\x32\x11.tbmatch.GameType\x12\r\n\x05nonce\x18\x02 \x01(\t\"g\n\x1eRedeemGameSessionTicketRequest\x12\x1f\n\x04game\x18\x01 \x01(\x0e\x32\x11.tbmatch.GameType\x12\r\n\x05nonce\x18\x02 \x01(\t\x12\x15\n\rbuild_version\x18\x05 \x01(\t\"\\\n\x1bGetGameSessionTicketRequest\x12\x1f\n\x04game\x18\x01 \x01(\x0e\x32\x11.tbmatch.GameType\x12\x1c\n\x14\x63lient_build_version\x18\x02 \x01(\t*!\n\x08GameType\x12\x15\n\x11GT_RISING_THUNDER\x10\x64\x32\xb1\x02\n\x0eSessionService\x12\x32\n\x05Login\x12\x15.tbmatch.LoginRequest\x1a\x0c.tbrpc.Empty\"\x04\xc8\xf3\x18\x00\x12g\n\x14GetGameSessionTicket\x12$.tbmatch.GetGameSessionTicketRequest\x1a#.tbmatch.GetGameSessionTicketResult\"\x04\xc8\xf3\x18\x01\x12V\n\x17RedeemGameSessionTicket\x12\'.tbmatch.RedeemGameSessionTicketRequest\x1a\x0c.tbrpc.Empty\"\x04\xc8\xf3\x18\x00\x12*\n\x06Logout\x12\x0c.tbrpc.Empty\x1a\x0c.tbrpc.Empty\"\x04\xc8\xf3\x18\x01')
  ,
  dependencies=[tbrpc_dot_tbrpc__pb2.DESCRIPTOR,])

_GAMETYPE = _descriptor.EnumDescriptor(
  name='GameType',
  full_name='tbmatch.GameType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='GT_RISING_THUNDER', index=0, number=100,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=434,
  serialized_end=467,
)
_sym_db.RegisterEnumDescriptor(_GAMETYPE)

GameType = enum_type_wrapper.EnumTypeWrapper(_GAMETYPE)
GT_RISING_THUNDER = 100



_LOGINREQUEST = _descriptor.Descriptor(
  name='LoginRequest',
  full_name='tbmatch.LoginRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='login', full_name='tbmatch.LoginRequest.login', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='password', full_name='tbmatch.LoginRequest.password', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='build_version', full_name='tbmatch.LoginRequest.build_version', index=2,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='__deprecated_remote_ip', full_name='tbmatch.LoginRequest.__deprecated_remote_ip', index=3,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=155,
)


_GETGAMESESSIONTICKETRESULT = _descriptor.Descriptor(
  name='GetGameSessionTicketResult',
  full_name='tbmatch.GetGameSessionTicketResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='game', full_name='tbmatch.GetGameSessionTicketResult.game', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=100,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nonce', full_name='tbmatch.GetGameSessionTicketResult.nonce', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=157,
  serialized_end=233,
)


_REDEEMGAMESESSIONTICKETREQUEST = _descriptor.Descriptor(
  name='RedeemGameSessionTicketRequest',
  full_name='tbmatch.RedeemGameSessionTicketRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='game', full_name='tbmatch.RedeemGameSessionTicketRequest.game', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=100,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nonce', full_name='tbmatch.RedeemGameSessionTicketRequest.nonce', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='build_version', full_name='tbmatch.RedeemGameSessionTicketRequest.build_version', index=2,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=235,
  serialized_end=338,
)


_GETGAMESESSIONTICKETREQUEST = _descriptor.Descriptor(
  name='GetGameSessionTicketRequest',
  full_name='tbmatch.GetGameSessionTicketRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='game', full_name='tbmatch.GetGameSessionTicketRequest.game', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=100,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='client_build_version', full_name='tbmatch.GetGameSessionTicketRequest.client_build_version', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=340,
  serialized_end=432,
)

_GETGAMESESSIONTICKETRESULT.fields_by_name['game'].enum_type = _GAMETYPE
_REDEEMGAMESESSIONTICKETREQUEST.fields_by_name['game'].enum_type = _GAMETYPE
_GETGAMESESSIONTICKETREQUEST.fields_by_name['game'].enum_type = _GAMETYPE
DESCRIPTOR.message_types_by_name['LoginRequest'] = _LOGINREQUEST
DESCRIPTOR.message_types_by_name['GetGameSessionTicketResult'] = _GETGAMESESSIONTICKETRESULT
DESCRIPTOR.message_types_by_name['RedeemGameSessionTicketRequest'] = _REDEEMGAMESESSIONTICKETREQUEST
DESCRIPTOR.message_types_by_name['GetGameSessionTicketRequest'] = _GETGAMESESSIONTICKETREQUEST
DESCRIPTOR.enum_types_by_name['GameType'] = _GAMETYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LoginRequest = _reflection.GeneratedProtocolMessageType('LoginRequest', (_message.Message,), dict(
  DESCRIPTOR = _LOGINREQUEST,
  __module__ = 'tbmatch.session_pb2'
  # @@protoc_insertion_point(class_scope:tbmatch.LoginRequest)
  ))
_sym_db.RegisterMessage(LoginRequest)

GetGameSessionTicketResult = _reflection.GeneratedProtocolMessageType('GetGameSessionTicketResult', (_message.Message,), dict(
  DESCRIPTOR = _GETGAMESESSIONTICKETRESULT,
  __module__ = 'tbmatch.session_pb2'
  # @@protoc_insertion_point(class_scope:tbmatch.GetGameSessionTicketResult)
  ))
_sym_db.RegisterMessage(GetGameSessionTicketResult)

RedeemGameSessionTicketRequest = _reflection.GeneratedProtocolMessageType('RedeemGameSessionTicketRequest', (_message.Message,), dict(
  DESCRIPTOR = _REDEEMGAMESESSIONTICKETREQUEST,
  __module__ = 'tbmatch.session_pb2'
  # @@protoc_insertion_point(class_scope:tbmatch.RedeemGameSessionTicketRequest)
  ))
_sym_db.RegisterMessage(RedeemGameSessionTicketRequest)

GetGameSessionTicketRequest = _reflection.GeneratedProtocolMessageType('GetGameSessionTicketRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETGAMESESSIONTICKETREQUEST,
  __module__ = 'tbmatch.session_pb2'
  # @@protoc_insertion_point(class_scope:tbmatch.GetGameSessionTicketRequest)
  ))
_sym_db.RegisterMessage(GetGameSessionTicketRequest)



_SESSIONSERVICE = _descriptor.ServiceDescriptor(
  name='SessionService',
  full_name='tbmatch.SessionService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=470,
  serialized_end=775,
  methods=[
  _descriptor.MethodDescriptor(
    name='Login',
    full_name='tbmatch.SessionService.Login',
    index=0,
    containing_service=None,
    input_type=_LOGINREQUEST,
    output_type=tbrpc_dot_tbrpc__pb2._EMPTY,
    options=_descriptor._ParseOptions(descriptor_pb2.MethodOptions(), _b('\310\363\030\000')),
  ),
  _descriptor.MethodDescriptor(
    name='GetGameSessionTicket',
    full_name='tbmatch.SessionService.GetGameSessionTicket',
    index=1,
    containing_service=None,
    input_type=_GETGAMESESSIONTICKETREQUEST,
    output_type=_GETGAMESESSIONTICKETRESULT,
    options=_descriptor._ParseOptions(descriptor_pb2.MethodOptions(), _b('\310\363\030\001')),
  ),
  _descriptor.MethodDescriptor(
    name='RedeemGameSessionTicket',
    full_name='tbmatch.SessionService.RedeemGameSessionTicket',
    index=2,
    containing_service=None,
    input_type=_REDEEMGAMESESSIONTICKETREQUEST,
    output_type=tbrpc_dot_tbrpc__pb2._EMPTY,
    options=_descriptor._ParseOptions(descriptor_pb2.MethodOptions(), _b('\310\363\030\000')),
  ),
  _descriptor.MethodDescriptor(
    name='Logout',
    full_name='tbmatch.SessionService.Logout',
    index=3,
    containing_service=None,
    input_type=tbrpc_dot_tbrpc__pb2._EMPTY,
    output_type=tbrpc_dot_tbrpc__pb2._EMPTY,
    options=_descriptor._ParseOptions(descriptor_pb2.MethodOptions(), _b('\310\363\030\001')),
  ),
])
_sym_db.RegisterServiceDescriptor(_SESSIONSERVICE)

DESCRIPTOR.services_by_name['SessionService'] = _SESSIONSERVICE

# @@protoc_insertion_point(module_scope)
