# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tbmatch/user.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from tbmatch import match_pb2 as tbmatch_dot_match__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='tbmatch/user.proto',
  package='tbmatch',
  syntax='proto2',
  serialized_pb=_b('\n\x12tbmatch/user.proto\x12\x07tbmatch\x1a\x13tbmatch/match.proto\"\x8c\x04\n\rPlayerSession\x12#\n\x05state\x18\x01 \x01(\x0e\x32\x14.tbmatch.PlayerState\x12\x38\n\x0c\x61\x63tive_match\x18\x02 \x01(\x0b\x32\".tbmatch.PlayerSession.ActiveMatch\x12)\n\x04menu\x18\x65 \x01(\x0b\x32\x1b.tbmatch.PlayerSession.Menu\x12+\n\x05queue\x18\x66 \x01(\x0b\x32\x1c.tbmatch.PlayerSession.Queue\x12+\n\x05lobby\x18g \x01(\x0b\x32\x1c.tbmatch.PlayerSession.Lobby\x1a\x32\n\x0b\x41\x63tiveMatch\x12\x10\n\x08match_id\x18\x01 \x01(\x03\x12\x11\n\tspectator\x18\x02 \x01(\x08\x1a\x82\x01\n\x04Menu\x12\x32\n\x06screen\x18\x01 \x01(\x0e\x32\".tbmatch.PlayerSession.Menu.Screen\"F\n\x06Screen\x12\x0b\n\x07SUMMARY\x10\x01\x12\x10\n\x0cPLAYER_STATS\x10\x02\x12\x12\n\x0ePLAYER_HISTORY\x10\x03\x12\t\n\x05STORE\x10\x04\x1a\x43\n\x05Queue\x12&\n\nmatch_type\x18\x01 \x01(\x0e\x32\x12.tbmatch.MatchType\x12\x12\n\nstart_time\x18\x02 \x01(\x03\x1a\x19\n\x05Lobby\x12\x10\n\x08lobby_id\x18\x01 \x01(\x03*6\n\x0bPlayerState\x12\x0b\n\x07PS_MENU\x10\x65\x12\x0c\n\x08PS_QUEUE\x10\x66\x12\x0c\n\x08PS_LOBBY\x10g')
  ,
  dependencies=[tbmatch_dot_match__pb2.DESCRIPTOR,])

_PLAYERSTATE = _descriptor.EnumDescriptor(
  name='PlayerState',
  full_name='tbmatch.PlayerState',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PS_MENU', index=0, number=101,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PS_QUEUE', index=1, number=102,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PS_LOBBY', index=2, number=103,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=579,
  serialized_end=633,
)
_sym_db.RegisterEnumDescriptor(_PLAYERSTATE)

PlayerState = enum_type_wrapper.EnumTypeWrapper(_PLAYERSTATE)
PS_MENU = 101
PS_QUEUE = 102
PS_LOBBY = 103


_PLAYERSESSION_MENU_SCREEN = _descriptor.EnumDescriptor(
  name='Screen',
  full_name='tbmatch.PlayerSession.Menu.Screen',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SUMMARY', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PLAYER_STATS', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PLAYER_HISTORY', index=2, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STORE', index=3, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=411,
  serialized_end=481,
)
_sym_db.RegisterEnumDescriptor(_PLAYERSESSION_MENU_SCREEN)


_PLAYERSESSION_ACTIVEMATCH = _descriptor.Descriptor(
  name='ActiveMatch',
  full_name='tbmatch.PlayerSession.ActiveMatch',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='match_id', full_name='tbmatch.PlayerSession.ActiveMatch.match_id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='spectator', full_name='tbmatch.PlayerSession.ActiveMatch.spectator', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=298,
  serialized_end=348,
)

_PLAYERSESSION_MENU = _descriptor.Descriptor(
  name='Menu',
  full_name='tbmatch.PlayerSession.Menu',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='screen', full_name='tbmatch.PlayerSession.Menu.screen', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _PLAYERSESSION_MENU_SCREEN,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=351,
  serialized_end=481,
)

_PLAYERSESSION_QUEUE = _descriptor.Descriptor(
  name='Queue',
  full_name='tbmatch.PlayerSession.Queue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='match_type', full_name='tbmatch.PlayerSession.Queue.match_type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='start_time', full_name='tbmatch.PlayerSession.Queue.start_time', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=483,
  serialized_end=550,
)

_PLAYERSESSION_LOBBY = _descriptor.Descriptor(
  name='Lobby',
  full_name='tbmatch.PlayerSession.Lobby',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='lobby_id', full_name='tbmatch.PlayerSession.Lobby.lobby_id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=552,
  serialized_end=577,
)

_PLAYERSESSION = _descriptor.Descriptor(
  name='PlayerSession',
  full_name='tbmatch.PlayerSession',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='state', full_name='tbmatch.PlayerSession.state', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=101,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='active_match', full_name='tbmatch.PlayerSession.active_match', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='menu', full_name='tbmatch.PlayerSession.menu', index=2,
      number=101, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='queue', full_name='tbmatch.PlayerSession.queue', index=3,
      number=102, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lobby', full_name='tbmatch.PlayerSession.lobby', index=4,
      number=103, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_PLAYERSESSION_ACTIVEMATCH, _PLAYERSESSION_MENU, _PLAYERSESSION_QUEUE, _PLAYERSESSION_LOBBY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=577,
)

_PLAYERSESSION_ACTIVEMATCH.containing_type = _PLAYERSESSION
_PLAYERSESSION_MENU.fields_by_name['screen'].enum_type = _PLAYERSESSION_MENU_SCREEN
_PLAYERSESSION_MENU.containing_type = _PLAYERSESSION
_PLAYERSESSION_MENU_SCREEN.containing_type = _PLAYERSESSION_MENU
_PLAYERSESSION_QUEUE.fields_by_name['match_type'].enum_type = tbmatch_dot_match__pb2._MATCHTYPE
_PLAYERSESSION_QUEUE.containing_type = _PLAYERSESSION
_PLAYERSESSION_LOBBY.containing_type = _PLAYERSESSION
_PLAYERSESSION.fields_by_name['state'].enum_type = _PLAYERSTATE
_PLAYERSESSION.fields_by_name['active_match'].message_type = _PLAYERSESSION_ACTIVEMATCH
_PLAYERSESSION.fields_by_name['menu'].message_type = _PLAYERSESSION_MENU
_PLAYERSESSION.fields_by_name['queue'].message_type = _PLAYERSESSION_QUEUE
_PLAYERSESSION.fields_by_name['lobby'].message_type = _PLAYERSESSION_LOBBY
DESCRIPTOR.message_types_by_name['PlayerSession'] = _PLAYERSESSION
DESCRIPTOR.enum_types_by_name['PlayerState'] = _PLAYERSTATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PlayerSession = _reflection.GeneratedProtocolMessageType('PlayerSession', (_message.Message,), dict(

  ActiveMatch = _reflection.GeneratedProtocolMessageType('ActiveMatch', (_message.Message,), dict(
    DESCRIPTOR = _PLAYERSESSION_ACTIVEMATCH,
    __module__ = 'tbmatch.user_pb2'
    # @@protoc_insertion_point(class_scope:tbmatch.PlayerSession.ActiveMatch)
    ))
  ,

  Menu = _reflection.GeneratedProtocolMessageType('Menu', (_message.Message,), dict(
    DESCRIPTOR = _PLAYERSESSION_MENU,
    __module__ = 'tbmatch.user_pb2'
    # @@protoc_insertion_point(class_scope:tbmatch.PlayerSession.Menu)
    ))
  ,

  Queue = _reflection.GeneratedProtocolMessageType('Queue', (_message.Message,), dict(
    DESCRIPTOR = _PLAYERSESSION_QUEUE,
    __module__ = 'tbmatch.user_pb2'
    # @@protoc_insertion_point(class_scope:tbmatch.PlayerSession.Queue)
    ))
  ,

  Lobby = _reflection.GeneratedProtocolMessageType('Lobby', (_message.Message,), dict(
    DESCRIPTOR = _PLAYERSESSION_LOBBY,
    __module__ = 'tbmatch.user_pb2'
    # @@protoc_insertion_point(class_scope:tbmatch.PlayerSession.Lobby)
    ))
  ,
  DESCRIPTOR = _PLAYERSESSION,
  __module__ = 'tbmatch.user_pb2'
  # @@protoc_insertion_point(class_scope:tbmatch.PlayerSession)
  ))
_sym_db.RegisterMessage(PlayerSession)
_sym_db.RegisterMessage(PlayerSession.ActiveMatch)
_sym_db.RegisterMessage(PlayerSession.Menu)
_sym_db.RegisterMessage(PlayerSession.Queue)
_sym_db.RegisterMessage(PlayerSession.Lobby)


# @@protoc_insertion_point(module_scope)
